# 项目配置
rbac:
  name: rbac-api
  #验证码类型（math:数组，char:字符）
  captchaType: char

# 项目启动端口号,文件上传大小限制
server:
  port: 3001
  multipart:
    # 文件最大
    max-file-size: 5MB
    # 设置总上传数据总大小
    max-request-size: 30MB

# log配置
logging:
  config: classpath:logback-spring.xml

# spring配置
spring:
  profiles:
    # dev/test/pro环境的切换
    active: dev
  # 时间格式化配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

# Sa-token配置
Sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位秒，-1代表永不过期
  timeout: 86400
  # token临时有效期 (指定时间内无操作就视为token过期)，单位秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 是否从cookie中读取token
  is-read-cookie: false
  # 是否从head中读取token
  is-read-head: true

# 访问白名单路径
secure:
  ignored:
    urls:
      - /api/
      - /swagger-ui/
      - /*.html
      - /*.html
      - /favicon.ico
      - /**/*.html
      - /**/*.css
      - /**/*.js
      - /swagger-resources/**
      - /v2/api-docs/**
      - /actuator/**
      - /static/**
      - /sysAdmin/login
      - /sysAdmin/captcha
      - /sysAdmin/logout


